### PR TITLE
Handle ASCII Error

### PR DESCRIPTION
**Pull request by dhilipsiva**
`binascii.Error`

### CODE REVIEW

**Comment by dhilipsiva** [comment]
Would it be possible for you to make a release ASAP? Thanks a ton in advance 😄

**Comment by dhilipsiva** [comment]
@jpulgarin 🔝

**Comment by dhilipsiva** [comment]
@jpulgarin ping

**Comment by jpulgarin** [comment]
Thanks for the pull request @dhilipsiva and sorry for the delay in getting back to you.

This looks good to me. Can you show me an example of a string that was causing this exception?

It'd be good if only the line that could plausibly raise this exception was inside the try block. Also, looks like you got rid of the `if auth_method.lower() == 'basic':` line. If you fix those two up and show me an example string I'll merge this in right away and make a release.

**Comment by dhilipsiva** [comment]
@jpulgarin While writing [single-page applications](https://github.com/appknox/irene/blob/develop/app/authenticators/irene.coffee) sometimes a HTTP request is being made before the application can fully initialize. So the HTTP_AUTHORIZATION header ends up being `undefined`. It fails in these situation. It will also fail when the header is calformed. Give me a moment, let me add that line back.

**Comment by jpulgarin** [comment]
Thanks @dhilipsiva. We should have only the offending line inside (which I assume is the b64decode method), inside the try block.

Also, I don't fully follow you with the authorization header being undefined. What actual value does the `basic_auth` variable have in these cases that would cause the `AsciiError` exception to be thrown?

**Comment by jpulgarin** [comment]
Hey @dhilipsiva I'm closing this for now since I'm not able to reproduce.

**Pull request closed without merging**
